### ISSUE TITLE
mqtt2influxdb on Pi5

### ISSUE THREAD

**Issue by maansch** [EdJoPaTo/mqtt2influxdb#29]
Hi,
try to install mqtt2influxdb with docker on Pi5 / bookworm.
But it didn't no work. 
log:
> $ docker pull ghcr.io/edjopato/mqtt2influxdb
> Using default tag: latest
> latest: Pulling from edjopato/mqtt2influxdb
> no matching manifest for linux/arm64/v8 in the manifest list entries

br
Marc-Andre

**Comment by EdJoPaTo** [comment]
The container is only available for amd64 currently and not arm64/v8 as cross compiling the container takes an hour on GitHub Action Runners.

Using the deb package works well for me, so I haven't looked into the long build times. I kinda hoped for arm64 runners to be available quicker, so the problem fixes itself, but sadly that didn't happen so far.

I hope this answer is at least somewhat helpful?

**Comment by maansch** [comment]
Hallo,
erst mal danke für die Antwort.

Kannst du mir sagen wie ich die deb im docker zu laufen bekomme?
Bin absoluter newbie zum Thema docker.

Danke
gr
Marc-Andre

**Comment by EdJoPaTo** [comment]
Ich persönlich würds ohne Docker auf nem Raspberry Pi OS (Debian) Pi laufen lassen. Der systemd service nutzt dynamische User und läuft damit ähnlich wie bei Docker Containern in einem eigenen Kontext. Kann aber auch verstehen, dass es Gründe dagegen gibt.

Eine deb kann mit `dpkg -i name.deb` installiert werden, bei `mqtt2influxdb` gibts dann besagten systemd service mit dazu. `systemctl edit mqtt2influxdb.service` ist hilfreich um die Environment variablen zu setzen. Danach `systemctl start mqtt2influxdb.service`.
Schau am besten mal nach ner Anleitung oder so dazu, das ist sehr wahrscheinlich detaillierter als ich das hier kann :innocent:
